# Generated by Django 5.2.13 on 2026-08-27 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('kind', models.CharField(choices=[('logo', 'Logótipo'), ('artwork', 'Arte aprovada'), ('template', 'Modelo reutilizável'), ('guide', 'Guia de marca'), ('document', 'Documento'), ('other', 'Outro')], default='other', max_length=20, verbose_name='tipo')),
                ('file', models.FileField(upload_to='uploads/brand_assets/', verbose_name='ficheiro')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('brand_colors', models.CharField(blank=True, help_text='Códigos hex separados por vírgula, ex.: #063F2B, #F4F0E8', max_length=255, verbose_name='cores da marca')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_brand_assets', to=settings.AUTH_USER_MODEL, verbose_name='carregado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_assets', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'material de marca',
                'verbose_name_plural': 'materiais de marca',
                'ordering': ['kind', 'name'],
                'indexes': [models.Index(fields=['user', 'kind'], name='assets_bran_user_id_5affae_idx')],
            },
        ),
    ]
