# Generated by Django 5.2.13 on 2026-06-16 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=20, unique=True, verbose_name='referência')),
                ('client_name', models.CharField(max_length=255, verbose_name='nome do cliente')),
                ('client_email', models.EmailField(max_length=254, verbose_name='email do cliente')),
                ('client_phone', models.CharField(blank=True, max_length=50, verbose_name='telefone do cliente')),
                ('client_company', models.CharField(blank=True, max_length=255, verbose_name='empresa')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='tamanho')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='material')),
                ('colors', models.CharField(blank=True, max_length=100, verbose_name='cores')),
                ('needs_design', models.BooleanField(default=False, verbose_name='necessita de design')),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgente')], default='normal', max_length=20, verbose_name='urgência')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/quote_files/', verbose_name='ficheiro anexo')),
                ('status', models.CharField(choices=[('received', 'Recebido'), ('reviewing', 'Em revisão'), ('awaiting_approval', 'Aguardando aprovação'), ('approved', 'Aprovada para produção'), ('in_production', 'Em produção'), ('ready', 'Pronto para levantamento'), ('delivered', 'Entregue')], default='received', max_length=30, verbose_name='estado')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='preço estimado')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='preço final')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='catalog.product', verbose_name='produto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to=settings.AUTH_USER_MODEL, verbose_name='utilizador')),
            ],
            options={
                'verbose_name': 'pedido de orçamento',
                'verbose_name_plural': 'pedidos de orçamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('changes_requested', 'Alterações solicitadas')], default='pending', max_length=30, verbose_name='estado')),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='uploads/artwork_proofs/', verbose_name='prova de arte')),
                ('designer_comment', models.TextField(blank=True, verbose_name='comentário do designer')),
                ('client_comment', models.TextField(blank=True, verbose_name='comentário do cliente')),
                ('requested_changes', models.TextField(blank=True, verbose_name='alterações solicitadas')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artwork', to='quotes.quoterequest', verbose_name='orçamento')),
            ],
            options={
                'verbose_name': 'aprovação de arte',
                'verbose_name_plural': 'aprovações de arte',
            },
        ),
    ]
