# Generated by Django 5.2.13 on 2026-06-22 16:45

from django.db import migrations, models


def map_status_choices(apps, schema_editor):
    QuoteRequest = apps.get_model("quotes", "QuoteRequest")
    mapping = {
        "awaiting_approval": "quoted",
    }
    for old, new in mapping.items():
        QuoteRequest.objects.filter(status=old).update(status=new)


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quoterequest_internal_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('received', 'Pedido recebido'), ('reviewing', 'Em análise'), ('quoted', 'Orçamentado'), ('approved', 'Aprovado'), ('in_production', 'Em produção'), ('ready', 'Pronto para entrega'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='received', max_length=30, verbose_name='estado'),
        ),
        migrations.RunPython(map_status_choices, migrations.RunPython.noop),
    ]
