# Generated by Django 5.2.13 on 2026-06-22 18:08

import django.db.models.deletion
from django.db import migrations, models


def migrate_quote_items(apps, schema_editor):
    QuoteRequest = apps.get_model("quotes", "QuoteRequest")
    QuoteItem = apps.get_model("quotes", "QuoteItem")
    for quote in QuoteRequest.objects.all():
        item = QuoteItem.objects.create(
            quote=quote,
            product=quote.product,
            description=quote.product.name if quote.product else "",
            quantity=quote.quantity,
            size=quote.size or "",
            material=quote.material or "",
            colors=quote.colors or "",
            needs_design=quote.needs_design,
            notes=quote.notes or "",
            position=0,
        )
        if quote.file:
            item.artwork_file.name = quote.file.name
            item.save(update_fields=["artwork_file"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productvariant'),
        ('quotes', '0003_alter_quoterequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='tamanho')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='material')),
                ('colors', models.CharField(blank=True, max_length=100, verbose_name='cores')),
                ('needs_design', models.BooleanField(default=False, verbose_name='necessita de design')),
                ('artwork_file', models.FileField(blank=True, null=True, upload_to='uploads/quote_item_files/', verbose_name='ficheiro de arte')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='preço unitário')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='catalog.product', verbose_name='produto')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='catalog.productvariant', verbose_name='variante')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quoterequest', verbose_name='orçamento')),
            ],
            options={
                'verbose_name': 'item do orçamento',
                'verbose_name_plural': 'itens do orçamento',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.RunPython(migrate_quote_items, migrations.RunPython.noop),
    ]
