# Generated by Django 5.2.13 on 2026-06-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quoteitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='file',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='material',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='needs_design',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='product',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='size',
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='notes',
            field=models.TextField(blank=True, verbose_name='observações gerais'),
        ),
    ]
