# Generated by Django 5.2.13 on 2026-06-23 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_remove_quoterequest_colors_remove_quoterequest_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['status'], name='quotes_quot_status_cead77_idx'),
        ),
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['user', '-created_at'], name='quotes_quot_user_id_e9037b_idx'),
        ),
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['-created_at'], name='quotes_quot_created_51e95a_idx'),
        ),
    ]
