# Generated by Django 5.2.13 on 2026-08-26 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_quoterequest_quotes_quot_status_cead77_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='price_approval_comment',
            field=models.TextField(blank=True, verbose_name='comentário da aprovação de preço'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='price_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='preço aprovado em'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='price_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_approvals', to=settings.AUTH_USER_MODEL, verbose_name='preço aprovado por'),
        ),
    ]
