# Generated by Django 5.2.13 on 2026-08-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_backfill_price_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='terms',
            field=models.TextField(blank=True, verbose_name='condições da proposta'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='proposta válida até'),
        ),
    ]
