# Generated by Django 5.2.13 on 2026-08-27 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_quoterequest_terms_quoterequest_valid_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkProofVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='versão')),
                ('file', models.FileField(upload_to='uploads/artwork_proofs/', verbose_name='ficheiro da prova')),
                ('designer_comment', models.TextField(blank=True, verbose_name='comentário do designer')),
                ('client_decision', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('changes_requested', 'Alterações solicitadas')], default='pending', max_length=30, verbose_name='decisão do cliente')),
                ('client_comment', models.TextField(blank=True, verbose_name='comentário do cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_versions', to='quotes.quoterequest', verbose_name='orçamento')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_proofs', to=settings.AUTH_USER_MODEL, verbose_name='carregado por')),
            ],
            options={
                'verbose_name': 'versão de prova',
                'verbose_name_plural': 'versões de prova',
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('quote', 'version'), name='unique_proof_version')],
            },
        ),
    ]
