# Generated by Django 5.2.13 on 2026-08-26 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_alter_order_user'),
        ('quotes', '0008_backfill_price_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Pedido registado'), ('status_changed', 'Estado actualizado'), ('price_approved', 'Preço aprovado'), ('artwork_proof_uploaded', 'Prova de arte enviada'), ('artwork_approved', 'Arte aprovada'), ('artwork_changes_requested', 'Alterações à arte pedidas'), ('converted_to_order', 'Convertido em encomenda'), ('payment_recorded', 'Pagamento registado'), ('payment_status_changed', 'Estado de pagamento actualizado')], max_length=40, verbose_name='acção')),
                ('from_status', models.CharField(blank=True, max_length=30, verbose_name='estado anterior')),
                ('to_status', models.CharField(blank=True, max_length=30, verbose_name='novo estado')),
                ('comment', models.TextField(blank=True, verbose_name='comentário')),
                ('is_internal', models.BooleanField(default=False, verbose_name='interno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='orders.order', verbose_name='encomenda')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='quotes.quoterequest', verbose_name='orçamento')),
            ],
            options={
                'verbose_name': 'evento de actividade',
                'verbose_name_plural': 'eventos de actividade',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['quote', '-created_at'], name='core_activi_quote_i_1c0a3c_idx'), models.Index(fields=['order', '-created_at'], name='core_activi_order_i_090469_idx')],
            },
        ),
    ]
