# Generated by Django 5.2.13 on 2026-09-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='action',
            field=models.CharField(choices=[('created', 'Pedido registado'), ('status_changed', 'Estado actualizado'), ('price_approved', 'Preço aprovado'), ('artwork_proof_uploaded', 'Prova de arte enviada'), ('artwork_approved', 'Arte aprovada'), ('artwork_changes_requested', 'Alterações à arte pedidas'), ('converted_to_order', 'Convertido em encomenda'), ('payment_recorded', 'Pagamento registado'), ('payment_status_changed', 'Estado de pagamento actualizado'), ('delivery_updated', 'Entrega actualizada'), ('delivery_confirmed', 'Entrega confirmada pelo cliente')], max_length=40, verbose_name='acção'),
        ),
    ]
