# Generated by Django 5.2.13 on 2026-06-22 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0003_alter_quoterequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=20, unique=True, verbose_name='referência')),
                ('product_name', models.CharField(blank=True, max_length=255, verbose_name='produto/serviço')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='tamanho')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='material')),
                ('colors', models.CharField(blank=True, max_length=100, verbose_name='cores')),
                ('needs_design', models.BooleanField(default=False, verbose_name='necessita de design')),
                ('client_file', models.FileField(blank=True, null=True, upload_to='orders/files/', verbose_name='ficheiro do cliente')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='preço final')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendente'), ('partial', 'Parcialmente pago'), ('paid', 'Pago')], default='pending', max_length=20, verbose_name='estado de pagamento')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor pago')),
                ('status', models.CharField(choices=[('received', 'Pedido recebido'), ('reviewing', 'Em análise'), ('quoted', 'Orçamentado'), ('approved', 'Aprovado'), ('in_production', 'Em produção'), ('ready', 'Pronto para entrega'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='received', max_length=30, verbose_name='estado')),
                ('delivery_method', models.CharField(blank=True, choices=[('pickup', 'Levantamento'), ('delivery', 'Entrega')], default='pickup', max_length=20, verbose_name='método de entrega')),
                ('delivery_address', models.TextField(blank=True, verbose_name='morada de entrega')),
                ('internal_notes', models.TextField(blank=True, verbose_name='notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='quotes.quoterequest', verbose_name='orçamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'encomenda',
                'verbose_name_plural': 'encomendas',
                'ordering': ['-created_at'],
            },
        ),
    ]
