# Generated by Django 5.2.13 on 2026-06-22 18:08

import django.db.models.deletion
from django.db import migrations, models


def migrate_order_items(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    OrderItem = apps.get_model("orders", "OrderItem")
    for order in Order.objects.all():
        item = OrderItem.objects.create(
            order=order,
            description=order.product_name or "",
            quantity=order.quantity,
            size=order.size or "",
            material=order.material or "",
            colors=order.colors or "",
            needs_design=order.needs_design,
            notes="",
            unit_price=order.final_price,
            position=0,
        )
        if order.client_file:
            item.artwork_file.name = order.client_file.name
            item.save(update_fields=["artwork_file"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productvariant'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='tamanho')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='material')),
                ('colors', models.CharField(blank=True, max_length=100, verbose_name='cores')),
                ('needs_design', models.BooleanField(default=False, verbose_name='necessita de design')),
                ('artwork_file', models.FileField(blank=True, null=True, upload_to='orders/item_files/', verbose_name='ficheiro de arte')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='preço unitário')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='encomenda')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='produto')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productvariant', verbose_name='variante')),
            ],
            options={
                'verbose_name': 'item da encomenda',
                'verbose_name_plural': 'itens da encomenda',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.RunPython(migrate_order_items, migrations.RunPython.noop),
    ]
