# Generated by Django 5.2.13 on 2026-09-01 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='confirmado pelo cliente em'),
        ),
        migrations.AddField(
            model_name='order',
            name='completion_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/delivery/', verbose_name='foto de conclusão'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='responsável pela entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='installation_required',
            field=models.BooleanField(default=False, verbose_name='requer instalação'),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data agendada'),
        ),
    ]
