# Generated by Django 5.2.13 on 2026-06-16 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='imagem')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='cliente')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='data de conclusão')),
                ('is_featured', models.BooleanField(default=False, verbose_name='em destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='catalog.servicecategory', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'item de portfólio',
                'verbose_name_plural': 'itens de portfólio',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
