# Generated by Django 5.2.13 on 2026-06-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('sector', models.CharField(blank=True, max_length=160, verbose_name='sector')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='logotipo')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_featured', models.BooleanField(default=False, verbose_name='em destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'parceiro',
                'verbose_name_plural': 'parceiros',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
