# Generated by Django 5.2.13 on 2026-06-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_partner_logo_data_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='image_data_url',
            field=models.TextField(blank=True, verbose_name='imagem embutida'),
        ),
    ]
