# Generated by Django 5.2.13 on 2026-06-16 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='preço')),
                ('items', models.JSONField(blank=True, default=list, help_text='Lista de itens incluídos no pacote.', verbose_name='itens incluídos')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/', verbose_name='imagem')),
                ('target_audience', models.CharField(blank=True, max_length=255, verbose_name='público-alvo')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='recorrente')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'pacote',
                'verbose_name_plural': 'pacotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('icon_name', models.CharField(blank=True, help_text='Identificador do ícone usado no frontend (ex: Printer, Shirt, Car).', max_length=100, verbose_name='nome do ícone')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='descrição curta')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='imagem')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'categoria de serviço',
                'verbose_name_plural': 'categorias de serviços',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='imagem')),
                ('materials', models.JSONField(blank=True, default=list, help_text='Lista de materiais disponíveis (ex: ["Algodão", "Poliéster"]).', verbose_name='materiais')),
                ('sizes', models.JSONField(blank=True, default=list, help_text='Lista de tamanhos disponíveis (ex: ["A4", "A3", "M"]).', verbose_name='tamanhos')),
                ('min_quantity', models.PositiveIntegerField(default=1, verbose_name='quantidade mínima')),
                ('lead_time', models.CharField(blank=True, max_length=100, verbose_name='prazo estimado')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='preço base')),
                ('pricing_complexity', models.CharField(choices=[('simple', 'Simples (preço base por unidade)'), ('complex', 'Complexo (requer orçamento manual)')], default='simple', max_length=20, verbose_name='tipo de precificação')),
                ('is_featured', models.BooleanField(default=False, verbose_name='em destaque')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.servicecategory', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['-is_featured', 'name'],
            },
        ),
    ]
