# Generated by Django 5.2.13 on 2026-06-22 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome da variante')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='preço')),
                ('image', models.ImageField(blank=True, null=True, upload_to='variants/', verbose_name='imagem')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'variante de produto',
                'verbose_name_plural': 'variantes de produtos',
                'ordering': ['position', 'name'],
            },
        ),
    ]
