# Generated by Django 5.2.13 on 2026-06-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image_data_url',
            field=models.TextField(blank=True, verbose_name='imagem embutida'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_data_url',
            field=models.TextField(blank=True, verbose_name='imagem embutida'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image_data_url',
            field=models.TextField(blank=True, verbose_name='imagem embutida'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='image_data_url',
            field=models.TextField(blank=True, verbose_name='imagem embutida'),
        ),
    ]
