# Generated by Django 5.2.13 on 2026-06-16 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='empresa')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='telefone')),
                ('nuit', models.CharField(blank=True, max_length=50, verbose_name='NUIT')),
                ('address', models.TextField(blank=True, verbose_name='endereço')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de cliente',
                'verbose_name_plural': 'perfis de clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
