# Generated by Django 5.2.13 on 2026-06-22 16:50

from django.db import migrations, models


def create_missing_profiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    ClientProfile = apps.get_model("accounts", "ClientProfile")
    for user in User.objects.all():
        ClientProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_create_allauth_email_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='billing_address',
            field=models.TextField(blank=True, verbose_name='morada de faturação'),
        ),
        migrations.RunPython(create_missing_profiles, migrations.RunPython.noop),
    ]
