# Generated by Django 5.2.13 on 2026-08-26 16:36

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.invoices.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_alter_order_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=24, unique=True, verbose_name='referência')),
                ('client_name', models.CharField(max_length=255, verbose_name='nome do cliente')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail do cliente')),
                ('client_phone', models.CharField(blank=True, max_length=50, verbose_name='telefone do cliente')),
                ('client_company', models.CharField(blank=True, max_length=255, verbose_name='empresa')),
                ('client_nuit', models.CharField(blank=True, max_length=50, verbose_name='NUIT')),
                ('billing_address', models.TextField(blank=True, verbose_name='morada de faturação')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='data de emissão')),
                ('due_date', models.DateField(default=apps.invoices.models.default_due_date, verbose_name='data de vencimento')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('issued', 'Emitida'), ('paid', 'Paga'), ('cancelled', 'Anulada')], default='draft', max_length=20, verbose_name='estado')),
                ('currency', models.CharField(default='MZN', max_length=3, verbose_name='moeda')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='subtotal')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='desconto')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='taxa de IVA (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='total')),
                ('recorded_amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='valor pago registado')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('terms', models.TextField(blank=True, verbose_name='condições')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='criada por')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='orders.order', verbose_name='encomenda')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'fatura',
                'verbose_name_plural': 'faturas',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10, verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='preço unitário')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice', verbose_name='fatura')),
            ],
            options={
                'verbose_name': 'item de fatura',
                'verbose_name_plural': 'itens de fatura',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoices_in_status_cec546_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', '-issue_date'], name='invoices_in_user_id_b011e2_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-issue_date'], name='invoices_in_issue_d_70a407_idx'),
        ),
    ]
