# Generated by Django 5.2.13 on 2026-06-22 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_remove_order_client_file_remove_order_colors_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('method', models.CharField(choices=[('cash', 'Dinheiro'), ('bank_transfer', 'Transferência bancária'), ('mpesa', 'M-Pesa'), ('emola', 'E-Mola'), ('other', 'Outro')], default='cash', max_length=30, verbose_name='método')),
                ('reference_code', models.CharField(blank=True, max_length=100, verbose_name='referência / transação')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('failed', 'Falhado'), ('refunded', 'Reembolsado')], default='completed', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='encomenda')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='registado por')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
