# Generated by Django 5.2.13 on 2026-06-23 04:36

import apps.payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_client_file_remove_order_colors_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, default=apps.payments.models._new_correlation_id, max_length=50, verbose_name='correlation ID'),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='telemóvel'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('manual', 'Manual'), ('mock', 'Mock'), ('mpesa', 'M-Pesa'), ('emola', 'E-Mola')], default='manual', max_length=20, verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='payload provider'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID transação provider'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'provider_transaction_id'], name='payments_pa_provide_26ee43_idx'),
        ),
    ]
